import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarPage from "@/components/NavBar";
import FooterPage from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-black dark:bg-black dark:text-white transition-colors duration-300">
        <Providers>
          <NavBarPage />
          {children}
          <FooterPage />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}